# Generated by Django 6.0.4 on 2026-06-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('imgUrl', models.URLField(max_length=1000)),
                ('category', models.CharField(choices=[('classic', 'Classic'), ('sport', 'Sport')], default='classic', max_length=20)),
            ],
        ),
    ]
